apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-js-pvc
spec:    
  volumeName: node-js-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""    
